# Generated by Django 3.2 on 2022-02-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0002_auto_20220202_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystaff',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='universityUniversityStaff', to='courses.university', verbose_name='Вуз'),
            preserve_default=False,
        ),
    ]
