# Generated by Django 3.2 on 2022-02-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_universitystaff_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitystaff',
            name='university',
        ),
        migrations.RemoveField(
            model_name='universitystaff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='UniversityStaff',
        ),
    ]
