# Generated by Django 3.2 on 2022-03-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee_organization_organizationcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_university',
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('UNIVERSITY', 'Высшее учебное заведение'), ('COMPANY', 'Компания')], default=1, max_length=12, verbose_name='Вид организации'),
            preserve_default=False,
        ),
    ]
