# Generated by Django 3.2 on 2022-03-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0007_alter_olympiad_organization'),
        ('courses', '0006_alter_course_organization'),
        ('organizations', '0001_initial'),
        ('users', '0006_auto_20220325_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationcity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organizationcity',
            name='organization',
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationEmployee', to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityStudent', to='organizations.city', verbose_name='Город'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationCity',
        ),
    ]
