# Generated by Django 3.2 on 2022-04-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220326_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
