# Generated by Django 3.2 on 2022-02-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220202_1932'),
        ('olympiads', '0002_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studentAnswer', to='users.student', verbose_name='Школьник'),
            preserve_default=False,
        ),
    ]
