# Generated by Django 3.2 on 2022-02-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220202_1932'),
        ('olympiads', '0003_answer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studentResult', to='users.student', verbose_name='Школьник'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiadSubject', to='olympiads.olympiad', verbose_name='Олимпиада')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectOlympiad', to='users.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет олимпиады',
                'verbose_name_plural': 'Предметы олимпиад',
            },
        ),
        migrations.CreateModel(
            name='CompanyCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityCompany', to='users.city', verbose_name='Город')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyCity', to='olympiads.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Город компании',
                'verbose_name_plural': 'Города компаний',
            },
        ),
    ]
