# Generated by Django 3.2 on 2022-03-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('olympiads', '0006_auto_20220325_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationOlympiad', to='organizations.organization', verbose_name='Организация'),
        ),
    ]
