# Generated by Django 3.2 on 2022-03-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0007_alter_olympiad_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olympiad',
            old_name='is_draft',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='is_draft',
            new_name='published',
        ),
    ]
