# Generated by Django 3.2 on 2022-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0008_auto_20220326_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='result',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
