# Generated by Django 3.2 on 2022-04-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0009_auto_20220326_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='certificate',
        ),
        migrations.AddField(
            model_name='result',
            name='finish_try_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания выполнения'),
        ),
        migrations.AddField(
            model_name='result',
            name='start_try_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала выполнения'),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(blank=True, choices=[('TAKEPART', 'Записался'), ('BEGIN', 'Начал выполнение'), ('SENT', 'Отправил на проверку'), ('CHECKED', 'Проверено')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='result',
            name='won',
            field=models.BooleanField(blank=True, null=True, verbose_name='Победил'),
        ),
    ]
