# Generated by Django 3.2 on 2022-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0010_auto_20220420_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='finish_try_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания выполнения'),
        ),
        migrations.AlterField(
            model_name='result',
            name='start_try_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала выполнения'),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('TAKEPART', 'Записался'), ('BEGIN', 'Начал выполнение'), ('SENT', 'Отправил на проверку'), ('CHECKED', 'Проверено')], default='TAKEPART', max_length=20, verbose_name='Статус'),
        ),
    ]
