# Generated by Django 3.2 on 2022-05-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0011_auto_20220427_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='time_to_pass',
            field=models.DurationField(blank=True, help_text='Например 04:00:00', null=True, verbose_name='Ограничение времени для решения'),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('TAKEPART', 'Записался(лась)'), ('BEGIN', 'В процессе выполнения'), ('SENT', 'Отправлено на проверку'), ('CHECKED', 'Проверено')], default='TAKEPART', max_length=20, verbose_name='Статус'),
        ),
    ]
