# Generated by Django 3.2 on 2022-05-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0012_auto_20220519_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='time_to_pass',
        ),
        migrations.RemoveField(
            model_name='result',
            name='finish_try_time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='start_try_time',
        ),
    ]
