# Generated by Django 3.2 on 2022-05-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0013_auto_20220524_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='time_to_pass',
            field=models.PositiveIntegerField(blank=True, help_text='в секундах', null=True, verbose_name='Ограничение времени для решения'),
        ),
        migrations.AddField(
            model_name='result',
            name='finish_try_time',
            field=models.PositiveIntegerField(blank=True, help_text='в секундах', null=True, verbose_name='Время окончания выполнения'),
        ),
        migrations.AddField(
            model_name='result',
            name='start_try_time',
            field=models.PositiveIntegerField(blank=True, help_text='в секундах', null=True, verbose_name='Время начала выполнения'),
        ),
    ]
