# Generated by Django 3.2 on 2022-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0015_auto_20220525_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='finish_try_time',
            field=models.BigIntegerField(blank=True, help_text='в секундах', null=True, verbose_name='Время окончания выполнения'),
        ),
        migrations.AddField(
            model_name='result',
            name='start_try_time',
            field=models.BigIntegerField(blank=True, help_text='в секундах', null=True, verbose_name='Время начала выполнения'),
        ),
    ]
