# Generated by Django 3.2 on 2022-05-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0016_auto_20220525_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='time_to_pass',
        ),
        migrations.RemoveField(
            model_name='result',
            name='finish_try_time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='start_try_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
