# Generated by Django 3.2 on 2022-05-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0017_auto_20220530_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Номер задания'),
        ),
    ]
