# Generated by Django 3.2 on 2022-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0018_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='published',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='result_published',
            field=models.BooleanField(default=False, verbose_name='Результаты опубликованы'),
        ),
    ]
