# Generated by Django 3.2 on 2022-02-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Полное название')),
                ('shortname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Вуз',
                'verbose_name_plural': 'Вузы',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('duration', models.CharField(choices=[('LESSMONTH', 'Меньше месяца'), ('MONTH', '1-2 месяца'), ('FEWMONTH', 'От двух месяцев до полугода'), ('HALFYEAR', 'От полугода до года'), ('YEARANDMORE', 'Год и более')], max_length=20, verbose_name='Длительность')),
                ('form', models.CharField(choices=[('ON', 'Онлайн'), ('OFF', 'Оффлайн'), ('BOTH', 'Смешанная')], max_length=20, verbose_name='Формат проведения')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('max_number_member', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество слушателей')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universityCourse', to='courses.university', verbose_name='Вуз')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
