# Generated by Django 3.2 on 2022-02-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220202_1932'),
        ('courses', '0002_universitystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='users.city', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseStudent', to='courses.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentCourse', to='users.student', verbose_name='Школьник')),
            ],
            options={
                'verbose_name': 'Школьник, записанный на курс',
                'verbose_name_plural': 'Школьники, записанные на курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseSubject', to='courses.course', verbose_name='Курс')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectCourse', to='users.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет курса',
                'verbose_name_plural': 'Предметы курсов',
            },
        ),
    ]
