# Generated by Django 3.2 on 2022-02-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220202_1932'),
        ('courses', '0003_auto_20220202_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityUniversity', to='users.city', verbose_name='Город'),
        ),
    ]
