# Generated by Django 3.2 on 2022-03-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee_organization_organizationcity'),
        ('courses', '0004_alter_university_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitystaff',
            name='university',
        ),
        migrations.RemoveField(
            model_name='universitystaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizationCourse', to='users.organization', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='UniversityStaff',
        ),
    ]
