# Generated by Django 3.2 on 2022-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, choices=[('LESSMONTH', 'Меньше месяца'), ('MONTH', '1-2 месяца'), ('FEWMONTH', 'От двух месяцев до полугода'), ('HALFYEAR', 'От полугода до года'), ('YEARANDMORE', 'Год и более')], max_length=20, null=True, verbose_name='Длительность'),
        ),
    ]
