# Generated by Django 3.2 on 2022-03-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_draft',
            new_name='published',
        ),
    ]
