# Generated by Django 3.2 on 2022-05-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='CourseCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityCourse', to='courses.city', verbose_name='Город')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseCity', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Город проведения курса',
                'verbose_name_plural': 'Города проведения курса',
            },
        ),
    ]
