# Generated by Django 3.2 on 2022-05-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_city_coursecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cityCourse', to='courses.city', verbose_name='Город проведения'),
        ),
        migrations.DeleteModel(
            name='CourseCity',
        ),
    ]
