# Generated by Django 3.2 on 2022-05-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20220520_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='form',
            field=models.CharField(choices=[('ON', 'Онлайн'), ('OFF', 'Оффлайн'), ('BOTH', 'Смешанный')], max_length=20, verbose_name='Формат проведения'),
        ),
    ]
