# Generated by Django 3.2 on 2022-05-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityCourse', to='courses.city', verbose_name='Город проведения'),
        ),
    ]
