# Generated by Django 3.2 on 2022-03-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Полное название')),
                ('shortname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('UNIVERSITY', 'Высшее учебное заведение'), ('COMPANY', 'Компания')], max_length=12, verbose_name='Вид организации')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityOrganization', to='organizations.city', verbose_name='Город')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationCity', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Город организации',
                'verbose_name_plural': 'Города организаций',
            },
        ),
    ]
