# Generated by Django 3.2 on 2022-03-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='kind',
            new_name='type',
        ),
    ]
