# Generated by Django 3.2 on 2022-03-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_kind_organization_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='type',
            new_name='kind',
        ),
    ]
