# Generated by Django 3.2 on 2022-05-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220519_2044'),
        ('organizations', '0005_rename_type_organization_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationcity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organizationcity',
            name='organization',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='OrganizationCity',
        ),
    ]
